// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBd_WGJCjDsgR7V2OlirHbjErH1iOqED4',
    appId: '1:561248405499:android:149c6b33b848946f5ded5e',
    messagingSenderId: '561248405499',
    projectId: 'triviamaster-2dae9',
    databaseURL: 'https://triviamaster-2dae9-default-rtdb.firebaseio.com',
    storageBucket: 'triviamaster-2dae9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB810izhblAIWVW49KgI5TMx5zJqrl7j5E',
    appId: '1:561248405499:web:a56d7edbd8f732295ded5e',
    messagingSenderId: '561248405499',
    projectId: 'triviamaster-2dae9',
    authDomain: 'triviamaster-2dae9.firebaseapp.com',
    databaseURL: 'https://triviamaster-2dae9-default-rtdb.firebaseio.com',
    storageBucket: 'triviamaster-2dae9.firebasestorage.app',
  );

}